ALTER TABLE books ADD COLUMN sync_status TEXT NOT NULL DEFAULT 'local';
ALTER TABLE books ADD COLUMN current_page INTEGER NOT NULL DEFAULT 0;
ALTER TABLE books ADD COLUMN total_pages INTEGER NOT NULL DEFAULT 0;